[2024-03-11 17:22:42,655][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=2, round_timeout=None)
[2024-03-11 17:22:46,218][flwr][INFO] - Flower VCE: Ray initialized with resources: {'GPU': 1.0, 'node:10.172.13.3': 1.0, 'accelerator_type:T550': 1.0, 'CPU': 16.0, 'object_store_memory': 4067171942.0, 'memory': 8134343886.0}
[2024-03-11 17:22:46,220][flwr][INFO] - Initializing global parameters
[2024-03-11 17:22:46,220][flwr][INFO] - Using initial parameters provided by strategy
[2024-03-11 17:22:46,220][flwr][INFO] - Evaluating initial parameters
[2024-03-11 17:22:47,279][flwr][INFO] - initial parameters (loss, other metrics): 182.19568634033203, {'accuracy': 0.1008}
[2024-03-11 17:22:47,279][flwr][INFO] - FL starting
[2024-03-11 17:22:47,279][flwr][DEBUG] - fit_round 1: strategy sampled 10 clients (out of 100)
[2024-03-11 17:22:48,357][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37326, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,418][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37322, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,431][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37326, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,491][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37322, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,504][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37320, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,769][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,777][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,786][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,856][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,918][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:48,919][flwr][DEBUG] - fit_round 1 received 0 results and 10 failures
[2024-03-11 17:22:49,371][flwr][INFO] - fit progress: (1, 182.19568634033203, {'accuracy': 0.1008}, 2.092360093000025)
[2024-03-11 17:22:49,371][flwr][DEBUG] - evaluate_round 1: strategy sampled 25 clients (out of 100)
[2024-03-11 17:22:49,598][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:49,668][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:49,747][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:49,810][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:49,906][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:49,944][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,012][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,247][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,290][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,313][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,319][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,327][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,335][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,429][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,543][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,578][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,579][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,678][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,683][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,684][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,684][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,704][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,798][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,798][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,802][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:50,803][flwr][DEBUG] - evaluate_round 1 received 0 results and 25 failures
[2024-03-11 17:22:50,803][flwr][DEBUG] - fit_round 2: strategy sampled 10 clients (out of 100)
[2024-03-11 17:22:51,062][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,104][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,175][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,180][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,233][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,334][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,338][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,363][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,375][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,387][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in launch_and_fit
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:51,387][flwr][DEBUG] - fit_round 2 received 0 results and 10 failures
[2024-03-11 17:22:51,858][flwr][INFO] - fit progress: (2, 182.19568634033203, {'accuracy': 0.1008}, 4.578766922000796)
[2024-03-11 17:22:51,858][flwr][DEBUG] - evaluate_round 2: strategy sampled 25 clients (out of 100)
[2024-03-11 17:22:52,064][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,125][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,239][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,243][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,269][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,373][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,507][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,511][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,511][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,618][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,662][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,734][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,789][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,869][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,883][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,907][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,935][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:52,990][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,059][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,063][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37331, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,075][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37317, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,092][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37319, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,111][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37321, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,112][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37330, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,126][flwr][ERROR] - [36mray::launch_and_evaluate()[39m (pid=37320, ip=10.172.13.3)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 159, in launch_and_evaluate
    client: Client = _create_client(client_fn, cid)
  File "/home/slu/anaconda3/envs/flower_tutorial/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
  File "/home/slu/Desktop/flower_tutorial/flower/client.py", line 84, in client_fn
    return FlowerClient(trainloader=trainloaders[int(cid)],
TypeError: __init__() got an unexpected keyword argument 'vallomodel_cfgader'
[2024-03-11 17:22:53,127][flwr][DEBUG] - evaluate_round 2 received 0 results and 25 failures
[2024-03-11 17:22:53,128][flwr][INFO] - FL finished in 5.84870148400023
[2024-03-11 17:22:53,128][flwr][INFO] - app_fit: losses_distributed []
[2024-03-11 17:22:53,128][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2024-03-11 17:22:53,128][flwr][INFO] - app_fit: metrics_distributed {}
[2024-03-11 17:22:53,128][flwr][INFO] - app_fit: losses_centralized [(0, 182.19568634033203), (1, 182.19568634033203), (2, 182.19568634033203)]
[2024-03-11 17:22:53,128][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.1008), (1, 0.1008), (2, 0.1008)]}
